version: "3.8"

services:
  adservice:
    build:
      context: ./src/adservice
    ports:
      - "9555:9555"
    container_name: adservice
   
      

  cartservice:
    build:
      context: ./src/cartservice/src
    ports:
      - "7070:7070"
    restart: always
    container_name: cartsrvice
    
     

  checkoutservice:
    build:
      context: ./src/checkoutservice
    ports:
      - "5050:5050"
    restart: always
    container_name: checkoutservice
    depends_on:
      - productcatalogservice
      - shippingservice
      - paymentservice
      - emailservice
      - currencyservice
      - cartservice

  currencyservice:
    build:
      context: ./src/currencyservice
    ports:
      - "7000:7000"
    restart: always
    container_name: currencyservice
   

  emailservice:
    build:
      context: ./src/emailservice
    ports:
      - "8080:8080"
    restart: always
    container_name: emailservice
    

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "8080:8080"
    restart: always
    container_name: frontend
    depends_on:
      - productcatalogservice
      - shippingservice
      - paymentservice
      - emailservice
      - currencyservice
      - cartservice
      - recommendationservice
      - checkoutservice
      - adservice
    

  loadgenerator:
    build:
      context: ./src/loadgenerator
    ports:
      - "9000:9000"
    restart: always
    container_name: loadgenerator
    depends_on:
      - frontend



  paymentservice:
    build:
      context: ./src/paymentservice
    ports:
      - "50051:50051"
    restart: always
    container_name: paymentservice
  

  productcatalogservice:
    build:
      context: ./src/productcatalogservice
    ports:
      - "3550:3550"
    restart: always
    container_name: productcatalogservice


  recommendationservice:
    build:
      context: ./src/recommendationservice
    ports:
      - "8080:8080"
    restart: always
    container_name: recommendationservice
    depends_on:
      - productcatalogservice
   

  shippingservice:
    build:
      context: ./src/shippingservice
    ports:
      - "50051:50051"
    restart: always
    container_name: shippingservice

